--escada corredor A1.04
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'A1'
AND COORD_X = 4
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 1

--escada corredor A1.05
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'A1'
AND COORD_X = 5
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 1

--escada corredor A2.05
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'A2'
AND COORD_X = 5
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 1

--escada corredor A2.06
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'A2'
AND COORD_X = 6
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 1

--escada corredor C1.04
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'C1'
AND COORD_X = 4
AND COORD_Y IN (10,11,12,13)
AND COORD_Z = 1


--escada corredor C1.05
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'C1'
AND COORD_X = 5
AND COORD_Y IN (10,11,12,13)
AND COORD_Z = 1

--escada corredor C2.05
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'C2'
AND COORD_X = 5
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 1

--escada corredor C2.06
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'C2'
AND COORD_X = 6
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 1


--------------/ANDAR 2/-----------------------

--escada corredor A1.04
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'A1'
AND COORD_X = 4
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 2

--escada corredor A1.05
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'A1'
AND COORD_X = 5
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 2

--escada corredor A2.05
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'A2'
AND COORD_X = 5
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 2

--escada corredor A2.06
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'A2'
AND COORD_X = 6
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 2

--escada corredor C1.04
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'C1'
AND COORD_X = 4
AND COORD_Y IN (10,11,12,13)
AND COORD_Z = 2


--escada corredor C1.05
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'C1'
AND COORD_X = 5
AND COORD_Y IN (10,11,12,13)
AND COORD_Z = 2

--escada corredor C2.05
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'C2'
AND COORD_X = 5
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 2

--escada corredor C2.06
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'C2'
AND COORD_X = 6
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 2





--------------/ANDAR 3/-----------------------
--escada corredor A1.04
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'A1'
AND COORD_X = 4
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 3

--escada corredor A1.05
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'A1'
AND COORD_X = 5
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 3

--escada corredor A2.05
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'A2'
AND COORD_X = 5
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 3

--escada corredor A2.06
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'A2'
AND COORD_X = 6
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 3

--escada corredor C1.04
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'C1'
AND COORD_X = 4
AND COORD_Y IN (10,11,12,13)
AND COORD_Z = 3


--escada corredor C1.05
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'C1'
AND COORD_X = 5
AND COORD_Y IN (10,11,12,13)
AND COORD_Z = 3

--escada corredor C2.05
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'C2'
AND COORD_X = 5
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 3

--escada corredor C2.06
UPDATE PRJ_LOCAIS SET ESCADA = 'T'
WHERE ZONA = 'C2'
AND COORD_X = 6
AND COORD_Y IN (1,2,3,4)
AND COORD_Z = 3